### PR TITLE
Making title scalable

### PR DESCRIPTION
**Pull request by blackcofla**
Making title resize to a custom window width properly (instead of cutting title text and adding ellipsis)

### CODE REVIEW

**Comment by dogo** [comment]
Hi @blackcofla 

Could you please give me a test scenario ?

I tried your fix with this title :
"Congratulations Superclarendon Superclarendon Superclarendon";

And apparently got no effect

**Comment by blackcofla** [comment]
Hi Diogo, nice to meet you!!!

Actually, you were right, I was able to overcome my problems by adjusting
the window width.

I'm simply trying to make the alert window to look the same in iPhone 4s
and iPad 2. I'm attaching screenshots of how it looks like before and after
my changes.

I'm not an IOS developer, I'm ruby developer using rubymotion and working
60 hours a week, so please trust me when I say that I appreciate your work
and your efforts to make this custom alert awesome.

Here some of the values I was using just in case:

#### MY CODE ######

alert = SCLAlertView.alloc.init
alert.windowWidth = <value>
alert.subTitleY = <value>
alert.subTitleHeight = <value>
alert.windowHeight = <value>
alert.setTitleFontFamily(<familyName>, withSize: <value>)
alert.setBodyTextFontFamily(<familyName>, withSize: <value>)
alert.setButtonsTextFontFamily(<familyName>, withSize: <value>)
alert.showError(self,
                title: 'Authorization error',
                subTitle: <message>,
                closeButtonTitle: 'Ok',
                duration: 0)


###### IPHONE 4S #########

### WIDTH: 240.0
### subTitleY: 76.0
### subTitleHeight: 103.0
### Height: 191.0
### titleFont: 15.9999961853027
### bodyFont: 12.7999954223633
### buttonsFont: 12.7999954223633


###### IPAD 2 #########

### WIDTH: 575.999877929688
### subTitleY: 84.3999938964844
### subTitleHeight: 121.199981689453
### Height: 209.199981689453
### titleFont: 38.3999938964844
### bodyFont: 30.7199935913086
### buttonsFont: 30.7199935913086


As you can see in my screenshots, there is some work to be done in terms of
Icon height and button height in order to look the same, but maybe simply
exposing API's for iconHeight and buttonHeight would be enough. Eventually
if I have enough time I could give it a try

Keep the hard work!!
Christian Segura

**Comment by dogo** [comment]
Hi @blackcofla nice to meet you too.

You can set now button size using ``` Objective-c @property (nonatomic) CGSize buttonSize;``` , if the iconHeight is a huge issue for you we can do something related

hehehe I can't see any screenshots attached :P

**Comment by blackcofla** [comment]
I originally sent you the reply via email hoping it would arrive to your
inbox with the screenshots. I'm on the way to the office but my Skype and
hangouts username is "blackcofla" as you could guess.

You can contact me there or send an email address where I can send you the
screenshots because I think it would be a nice improvement to your alert

Best regards,
Christian

**Comment by dogo** [comment]
Added on Skype. I removed you username from your post, for privacy reasons :P

**Comment by blackcofla** [comment]
Closing pull request

**Comment by robotsu** [comment]
@blackcofla

**Pull request closed without merging**
