### PR TITLE
New Feature: Horizontal alignment for buttons.

### PR DESCRIPTION
**Pull request by jaespinmora**
This new feature allows users to align buttons horizontally instead of vertically. This new feature can be tested on Example Project where are some new examples with horizontal buttons.

It's only necessary to add this code line after init the alert.
`[alert setHorizontalButtons:YES];`

### CODE REVIEW

**Comment by dogo** [comment]
Thanks @jaespinmora

**Comment by jaespinmora** [comment]
Hi, When do you think you will merge develop with master and release a new version of the pod?

**Comment by dogo** [comment]
1.0.3 is live

**Comment by jaespinmora** [comment]
Thanks @dogo

**Pull request merged**
