### PR TITLE
Change play sound class

### PR DESCRIPTION
**Pull request by Liqiankun**
Hello,First of all I wanna say "I Love SCLAlertView!".I find a issue. When you are listening music,you display SCLAlertView which one with sound at another APP,then the music would stop. I used AudioServicesPlaySystemSound(_soundID) play sound,fixed this issue. I think AudioServicesPlaySystemSound play sounds would be better,cuz the sound is short. My English is not good,hopefully you get my words. Thanks.

### CODE REVIEW

**Comment by dogo** [comment]
I'll take a look on this later.  Thanks

**Comment by Liqiankun** [comment]
My pleasure!

**Comment by Liqiankun** [comment]
Does it work?

**Comment by dogo** [comment]
Sorry about the delay. Sounds good

**Pull request merged**
