### PR TITLE
Fluent style support extension

### PR DESCRIPTION
**Pull request by lolgear**
Text field builder added
Button builder added
Readme updated
constant title top fixed

### CODE REVIEW

**Comment by dogo** [comment]
Still on master and the constant fix its not needed I think, I fixed on develop branch

**Comment by lolgear** [comment]
@dogo, nevertheless, it still needs manual merging, so, you could drop any inappropriate features

**Comment by lolgear** [comment]
@dogo, "lolgear  wants to merge 7 commits into dogo:develop from lolgear:master" github said

**Comment by dogo** [comment]
@lolgear "This branch has conflicts that must be resolved.
Use the command line to resolve conflicts before continuing."

**Comment by lolgear** [comment]
#193

**Pull request closed without merging**
