### PR TITLE
Support for custom window width. New bounce animation

### PR DESCRIPTION
**Pull request by javikr**
- Support for custom window width (new initializer)
- New bounce animation (available from iOS 7 and up)
- Bugfix: text view height

### CODE REVIEW

**Comment by dogo** [comment]
HI @javikr , could please split your pull request as : bounce animation and custom width. 

I really did not liked your implementation of custom width, it's too aggressive with the lib structure.
Probably I will use your code as reference

**Comment by dogo** [comment]
@javikr I made the bounce integration my self using your code. thanks

**Comment by javikr** [comment]
ok.

Thanks ;)

Best,
Javier

**Comment by dogo** [comment]
@javikr I'm closing this PR since I'm working on "feature/custom-width" branch

**Pull request closed without merging**
